name: mindful_dart_util
description: Mindful Software Utilities that only depend on Dart.
homepage: https://mindfulsoftware.com
repository: https://github.com/michaelbushe/mindful_dart_util
version: 0.10.0

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  args: ^2.5.0
  clock: ^1.1.1
  crypto: ^3.0.3
  io: ^1.0.4
  logging: ^1.2.0
  path: ^1.9.0

dev_dependencies:
  build_runner: ^2.4.11
  mindful_analysis: ^1.0.0+2
  mocktail: ^1.0.4
  mockito: ^5.4.4
  test: ^1.24.6
