name: mindful_dart_util
description: Mindful Software Utilities that only depend on Dart.
homepage: https://mindfulsoftware.com
repository: https://github.com/michaelbushe/mindful_dart_util
version: 0.4.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.22.2
  very_good_analysis: ^3.1.0
