name: mindful_dart_util
description: Mindful Software Utilities that only depend on Dart.
homepage: https://mindfulsoftware.com
repository: https://github.com/michaelbushe/mindful_dart_util
version: 0.6.3

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  args: ^2.4.0

dev_dependencies:
  mindful_analysis: ^1.0.0+2
  mocktail: ^0.3.0
  test: ^1.24.1
