name: mindful_dart_util
description: Mindful Software Utilities that only depend on Dart.
homepage: https://mindfulsoftware.com
repository: https://github.com/michaelbushe/mindful_dart_util
version: 0.5.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.23.1
  mindful_analysis: ^1.0.0+2
